spring:
  datasource:
    url: "jdbc:mariadb://172.17.0.1:3305/FantaParrocchieDB"
    username: "root"
    password: "mypass"
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: "FantaParocchie"
  jpa:
    hibernate:
      ddl-auto: create
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
flyway:
  baseline-on-migrate: true
  baseline-version: "1.0"
server:
  context-path: /rest
logging:
  level: debug
