spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/FantaParrocchieDB"
    username: "root"
    password: "toor"
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: "FantaParocchie"
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
flyway:
  baseline-on-migrate: true
  baseline-version: "1.0"
server:
  context-path: /rest
